version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lol
      MYSQL_DATABASE: semestralne_zadanie
      MYSQL_USER: webte
      MYSQL_PASSWORD: webte
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  frontend:
    build:
      context: ./frontend
#    ports:
#      - '80:80'
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
#    ports:
#      - '3000:80'
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
volumes:
  mysql_data:
  frontend_dist:
