version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lol
      MYSQL_DATABASE: semestralne_zadanie
      MYSQL_USER: webte
      MYSQL_PASSWORD: webte
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: